name: Client CI

on:
  push:
    paths:
      - "client/**"
      - ".github/workflows/client_ci.yml"
      - ".github/workflows/service_ci_template.yml"
      - "package.json"
      - "package-lock.json"
  pull_request:
    paths:
      - "client/**"
      - ".github/workflows/client_ci.yml"
      - ".github/workflows/service_ci_template.yml"
      - "package.json"
      - "package-lock.json"

jobs:
  ci:
    uses: ./.github/workflows/service_ci_template.yml
    permissions:
      checks: write
      contents: read
      security-events: write
    with:
      service_name: Client
      service_path: client
      docker_image: rsgsystem-client
