name: Server CI

on:
  push:
    paths:
      - "server/**"
      - ".github/workflows/server_ci.yml"
      - ".github/workflows/service_ci_template.yml"
      - "package.json"
      - "package-lock.json"
  pull_request:
    paths:
      - "server/**"
      - ".github/workflows/server_ci.yml"
      - ".github/workflows/service_ci_template.yml"
      - "package.json"
      - "package-lock.json"

jobs:
  ci:
    uses: ./.github/workflows/service_ci_template.yml
    with:
      service_name: Server
      service_path: server
      docker_image: rsgsystem-server
